### ISSUE TITLE
differences between this version and Universal-IFR-Extractor

### ISSUE THREAD

**Issue by BoringBoredom** [LongSoft/IFRExtractor-RS#10] opened 2022-11-10 19:36 UTC
There are a few things in this version that completely break my [parser](https://github.com/BoringBoredom/UEFI-Editor/blob/master/assets/js/main.js) or require work-arounds (1, 2) and some things I'd like to see reimplemented (3, 4).

1. The new `Help`strings potentially span across multiple lines. **I don't have a _reliable_ work-around for multi line entries.**
![image](https://user-images.githubusercontent.com/16615327/201181487-04153f18-aed6-4622-bc85-f49037f48515.png)
2. `End If {29 02}` and `End One Of {29 02}` have been unified to `End  { 29 02 }`. I can work around this issue **if the indentation level is always guaranteed to be representative of the scope**. Is it?
3. The switch from HEX to DEC for things like QuestionId seems pointless due to working with HEX strings anyways.
4. The defaults of `One Of` options are not shown anymore (identified by this byte, afaik `{ 00 00 00 00 XX 00 00 }`).

**Comment by NikolajSchlej** [comment] 2022-11-11 11:00
1. We do believe those strings to be useful though, as sometimes just the prompt is not enough to understand what a given setting is supposed to be doing. However, we can implement a mode that will not output them and that parser can then use it.
- [ ] Implement a mode that doesn't put Help strings into the resulting ifr.txt file(s).

2. As you can see, the End opcode ```{29 02}``` is the same for both. Every ```End``` opcode reduces the current scope by 1 every time, and indentation always represents the scope for UEFI HII parsing mode (Framework HII mode has very minimal manual indentation done for ```FormSet```, ```Form```, ```EndFormSet``` and ```EndForm``` OpCodes only).

3. Matter of preference, but I agree that making all ```Id``` numbers hex makes sense.
- [ ] Ensure that all ```Id``` numbers are printed as hex, not dec

4. Indeed, the flags are in the output, but not interpreted. Will be fixed, along with other similar "flags are not interpreted sometimes, which makes the output less readable" issues.
- [ ] Interpret known values of various ```Flags```.

**Comment by BoringBoredom** [comment] 2022-11-11 11:45
1. I agree, it's useful information and I'd prefer to have it, too. Maybe escaped line feeds would be a reasonable compromise? As long as it stays on the same line I don't mind any solution.
2. Sometimes a `Suppress If` condition is hundreds of lines above the variable or sometimes there are even multiple suppressions and it's very time consuming to manually figure that out. That's why I wanted to make sure indentations always match the scope so I can automate it and append the potential suppression list to each variable to make unsuppressing easier.

**Comment by BoringBoredom** [comment] 2022-11-14 01:15
Another thing I noticed missing is `Size`. Is the following correct? Prompts without `max` are of size 1, while prompts like `OneOf` or `Numeric`, which have a `max`, are of the smallest size that fits `max`.

E.g.:
Size 1 for 0 -15
Size 2 for 16-255
Size 4 for 256-65535
Size 8 for 65536-4294967295

**Comment by NikolajSchlej** [comment] 2022-11-14 11:26
Can you please provide an example of such prompts parsed by IFRExtractor-RS and Universal IFR Extractor, so I could see the difference you've spotted?

**Comment by BoringBoredom** [comment] 2022-11-15 00:06
Something is wrong with the verbose output

![image](https://user-images.githubusercontent.com/16615327/201793549-808f82b2-a51f-4877-9fbc-7177191ddf00.png)

**Comment by NikolajSchlej** [comment] 2022-11-15 10:35
On the last screenshot, it's a bug with the Display implementation (data is correct, printout is not), will be fixed.
- [ ] Fix Display implementation for IfrOpCode

On the former, I see if I can add that information.
- [ ] Add Size to OpCodes that have it in Universal-IFR-Extractor

**Comment by BoringBoredom** [comment] 2022-11-17 00:28
```
DisableIf  { 9E 02 }
Disable If {1E 82}

GrayOutIf  { 99 02 }
Gray Out If {19 82}

SuppressIf  { 8A 02 }
Suppress If {0A 82}

Numeric Prompt: [...] { 87
Numeric: [...] {07
```

CheckBox and OneOf OpCode HEX outputs are also wrong. I suspect the issue impacts most/all OpCodes.

**Comment by NikolajSchlej** [comment] 2022-11-17 01:25
Yep, it's a bug in Display trait for OpCode structure, so everything that starts a new scope is affected.

**Comment by NikolajSchlej** [comment] 2022-11-17 12:04
Everything but multiline text output (required some special string escape dances) and interpretation of Flags (requires a bigger chunk of development time) should now be fixed in https://github.com/LongSoft/IFRExtractor-RS/commit/9e193459c8156728fe073ff07b4ee1776e3122b7

**Comment by BoringBoredom** [comment] 2022-11-27 06:36
Is there any ETA? I want to rewrite my parser and wondered if I should wait or still use the old version in case this will take a while.

**Comment by NikolajSchlej** [comment] 2022-11-27 10:27
Please test that latest commit and confirm that the bugs I've marked as fixed are indeed fixed (you can get Windows binaries for it [here](https://github.com/LongSoft/IFRExtractor-RS/suites/9359772153/artifacts/440654215)).

There are no ETAs because both me and @vit9696 are having a lot of job-related fun lately, but I'll try to find some time to resolve the remaining two issues here before the end of the year.

You can safely continuing using the previous tool until we get boards and firmwares that it could not properly parse, which I do not expected to become an issue for a while (as UEFI IFR format is almost done, no new opcodes introduced for several years).

**Comment by BoringBoredom** [comment] 2022-11-28 08:27
![image](https://user-images.githubusercontent.com/16615327/204228035-2ae45d68-57d7-4a6a-bfd1-09841e05d4c8.png)

A new thing I noticed is the offset is not matching. It's an issue in the previous iteration (1.4), too.

The rest seems to be fixed at first glance.

**Comment by NikolajSchlej** [comment] 2022-11-28 14:55
Can you attach the EFI file for the offset issue?

**Comment by BoringBoredom** [comment] 2022-11-28 16:59
https://dlcdnets.asus.com/pub/ASUS/mb/BIOS/ROG-STRIX-Z690-A-GAMING-WIFI-D4-ASUS-2103.zip

**Comment by NikolajSchlej** [comment] 2022-11-28 18:21
Confirmed, all offsets are exactly 4 bytes off due to start offset being determined incorrectly, will be fixed.
- [ ] Fix start offset being 4 bytes too low

**Comment by NikolajSchlej** [comment] 2022-12-24 08:33
Got the Default and MfgDefault flags working in the latest commit, will release 1.5.0 soon.

**Comment by BoringBoredom** [comment] 2022-12-24 23:35
I don't need this feature anymore: `Implement a mode that doesn't put Help strings into the resulting ifr.txt file(s)`

---
I'd like to have a version timestamp at the beginning of the file (e.g. `Extracted with IFR-Extractor-RS v1.5.0`). It'd help avoid issues in applications that depend on it.

**Comment by NikolajSchlej** [comment] 2023-01-08 06:46
Done with that version number feature, will also be in 1.5.0 soon.

**Closed** 2023-01-08 06:46 UTC
